# @Author: 周长安
# @Date:   2017-03-15 12:40:15
# @Email:  zchangan@163.com
# @Last modified by:   周长安
# @Last modified time: 2017-03-15 13:18:58



sudo: false
language: node_js
node_js:
  - "6"
  - "5"
  - "4"
  - "iojs"
  - "0.12"
  - "0.10"
script: npm test
